name: Post Publish Tasks

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Update version in package.json
        working-directory: ./quick-filter-table
        run: |
          npm version patch
      - name: Set variables
        id: set-vars
        run: |
          # For release events, github.ref_name is the release tag (e.g. 1.0.0) and
          # github.event.release.target_commitish is the branch/tag/commit that the
          # tag was created from (e.g. main).
          #
          # For workflow_dispatch events, github.ref_name is the branch/tag/commit
          # that the workflow was dispatched on.
          base_branch="${{ github.event_name == 'release' && github.event.release.target_commitish || github.ref_name }}"
          base_branch_no_slashes=$(echo $base_branch | tr '/' '-')
          echo "base-branch=$base_branch" >> "$GITHUB_OUTPUT"
          echo "branch-name=${{ inputs.branch-prefix }}update-project-version-$base_branch_no_slashes" >> "$GITHUB_OUTPUT"
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        env:
          action-url: https://github.com/${{ github.action_repository }}/tree/${{ github.action_ref }}/update-project-version
        with:
          base: ${{ steps.set-vars.outputs.base-branch }}
          branch: ${{ steps.set-vars.outputs.branch-name }}
          commit-message: "chore: update version in package.json"
          title: "chore: update version in package.json"
          # The workflow log currently points to the run, not the specific job
          # within that run. Linking to a specific job requires the numeric job id,
          # which is not available in the github context.
          # https://stackoverflow.com/questions/71240338/obtain-job-id-from-a-workflow-run-using-contexts
          body: |
            This PR updates the versions of the following NPM projects:

            - quick-filter-table

            ---

            This PR was generated by [.github/workflows/release.yml](${{ env.action-url }}). View the [workflow log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
